---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - name: mpod.kb.io
    objectSelector:
      matchExpressions:
        - key: app.sanmuyan.com/injection
          operator: In
          values:
            - "true"