# permissions for end users to view appconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app-operator
    app.kubernetes.io/part-of: app-operator
    app.kubernetes.io/managed-by: kustomize
  name: appconfig-viewer-role
rules:
- apiGroups:
  - app.sanmuyan.com
  resources:
  - appconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.sanmuyan.com
  resources:
  - appconfigs/status
  verbs:
  - get
