apiVersion: app.sanmuyan.com/v1
kind: AppConfig
metadata:
  labels:
    app.kubernetes.io/name: appconfig
    app.kubernetes.io/instance: appconfig-sample
    app.kubernetes.io/part-of: app-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: app-operator
  name: appconfig-sample
spec:
  # TODO(user): Add fields here
