apiVersion: app.sanmuyan.com/v1
kind: AppConfig
metadata:
  labels:
    app.kubernetes.io/name: appconfig
    app.kubernetes.io/instance: appconfig-sample
    app.kubernetes.io/part-of: app-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: app-operator
  name: appconfig-sample
  annotations:
    app.sanmuyan.com/canary-ingress: "false"
    app.sanmuyan.com/canary-rolling-weight: "false"
    app.sanmuyan.com/strict-update: "false"
    app.sanmuyan.com/protected: "false"
    app.sanmuyan.com/strict-release: "false"
    app.sanmuyan.com/deployment-config: |
      {"spec":{"template":{"spec":{"containers":[{"name":"app","resources":{"requests":{"cpu":"100m","memory":"100Mi"}}}]}}}}
    app.sanmuyan.com/injection-containers: |
      [{"name":"proxy","image":"sanmuyan/ubuntu:not-exit"}]
    app.sanmuyan.com/ingress-annotations: |
      [{"nginx.ingress.kubernetes.io/ssl-redirect": "true"},{"nginx.ingress.kubernetes.io/proxy-body-size": "256m"}]
spec:
  deployConfigs:
    - image: sanmuyan/ubuntu:not-exit
      name: appconfig-sample-canary
      replicas: 1
      type: canary
    - image: sanmuyan/ubuntu:not-exit
      name: appconfig-sample-stable
      replicas: 1
      type: stable
  ingress:
    enable: true
    host: www.example.com
  service:
    enable: true
    port: 8080
